<?php
$app = builder()->get_application();
$secret_keys = file_get_contents("https://api.wordpress.org/secret-key/1.1/salt/");
$cache = isset($app->env->wordpress["cache"])? "define('WP_CACHE', {$app->env->wordpress["cache"]});" : "";
$debug = isset($app->env->wordpress["debug"])? "define('WP_DEBUG', true);" : "";
$wp_lang = isset($app->env->wordpress["wp_lang"])? "define('WP_LANG', '{$app->env->wordpress["wp_lang"]}');" : "";

$site_url = isset($app->env->wordpress["url"])? "'{$app->env->wordpress["url"]}'":"'http://' . \$_SERVER['SERVER_NAME']";
if(isset($app->env->wordpress["base_uri"])){
  $site_url .= " . '" . $app->env->wordpress['base_uri'] . "'";
}
$wp_home = $site_url;
if(isset($app->env->wordpress["wp_own_directory"]) && $app->env->wordpress["wp_own_directory"] === true){
  $site_url .= " . '/wordpress'";
}

return <<<EOT
<?php
/*
  Generated by Pomander Wordpress
  Change configuration at deploy folder then run `pom wp_config` to update this file.
 */
define('DB_NAME', '{$app->env->database["name"]}');
define('DB_USER', '{$app->env->database["user"]}');
define('DB_PASSWORD', '{$app->env->database["password"]}');
define('DB_HOST', '{$app->env->database["host"]}');
define('DB_CHARSET', '{$app->env->database["charset"]}');
define('DB_COLLATE', '');
{$secret_keys}
\$table_prefix = '{$app->env->wordpress["db_prefix"]}';
{$wp_lang}
if( !defined('ABSPATH') ) define('ABSPATH', dirname(__FILE__).'/wordpress/');
define('WP_SITEURL', {$site_url});
define('WP_HOME', {$wp_home});
define('WP_CONTENT_DIR', dirname(ABSPATH) . '/public');
define('WP_CONTENT_URL', WP_HOME . '/public');
define('WP_PLUGIN_DIR', dirname(ABSPATH) . '/vendor/plugins');
define('WP_PLUGIN_URL', WP_HOME . '/vendor/plugins');
define('PLUGINDIR', WP_PLUGIN_DIR);
{$cache}
{$debug}
require_once(ABSPATH . 'wp-settings.php');
?>
EOT;

?>